title: Aidana Nurakhmetova
logo: assets/img/main_photo.jpeg
description: Machine Learning Engineer
# show_downloads: true
theme: jekyll-theme-minimal

# Social icons
footer_links:
  github_username: Aydana1
  linkedin_username: nurakhmetova
