title: Aidana Nurakhmetova
logo: assets/img/main_photo.jpeg
description: Machine Learning Engineer
# show_downloads: true
theme: jekyll-theme-minimal

# Social icons
github_username: Aydana1
linkedin_username: <img width="50" height="50" src=assets/img/LinkedIN_black.png href="https://www.linkedin.com/in/nurakhmetova/">
