title: Aidana Nurakhmetova
author: Aidana Nurakhmetova
logo: assets/img/main_photo.jpeg
description: Machine Learning Engineer
show_downloads: true
theme: jekyll-theme-minimal

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

# Social icons
social-network-links:
  github: Aydana1
  linkedin: nurakhmetova
