title: Aidana Nurakhmetova
logo: main_photo.jpeg
description: Machine Learning Engineer Graduate
# show_downloads: true
theme: jekyll-theme-minimal

# Social icons
github_username: Aydana1
linkedin_username: nurakhmetova
